In [1]:
import numpy as np
arr=np.arange(1,10).reshape(3,3)
arr1=np.arange(1,10).reshape(3,3)
print(arr)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#addtion fnction
np.add(arr,arr1)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [3]:
#multiply function
np.multiply(arr,arr1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [4]:
#division function
np.divide(arr,arr1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
#subtract function
np.subtract(arr,arr1)## element multiplcation

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
## be can apply all work using oprator
## matrix multiplication
arr1.dot(arr)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [7]:
np.max(arr)##provide maximum element.

9

In [8]:
arr.argmax()

8

In [9]:
np.max(arr,axis=1)##max in column

array([3, 6, 9])

In [10]:
np.max(arr,axis=0)## max in row;

array([7, 8, 9])

In [11]:
np.sum(arr)## sum of all element of array

45

In [12]:
np.sum(arr,axis=1)## sum of all column element of array 

array([ 6, 15, 24])

In [13]:
np.sum(arr,axis=0)## sum of all row element of array

array([12, 15, 18])

In [14]:
np.min(arr)## give minimum element of array

1

In [16]:
np.min(arr,axis=1)## give minimum column element of array

array([1, 4, 7])

In [17]:
np.min(arr,axis=0)## give minimum row element of array

array([1, 2, 3])

In [18]:
arr.argmin()## return index of minimum element.

0

In [19]:
np.mean(arr)## find avrage of array

5.0

In [20]:
np.sqrt(arr)##gives squre root of every element.

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [21]:
np.std(arr)##stander division 

2.581988897471611

In [22]:
np.exp(arr)##Return exponential value

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [23]:
np.log(arr)## return log value of one another element

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [25]:
np.log10(arr)## return log10 value one another element.

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])