In [1]:
import numpy as np

In [3]:
##create 1d array

In [5]:
d1_array=np.array([1,2,3])
print(d1_array)

[1 2 3]


In [6]:
##create 2d array

In [32]:
d2_array=np.array([[1,2,3],[4,5,6]])
print(d2_array)

[[1 2 3]
 [4 5 6]]


In [9]:
type(d1_array)

numpy.ndarray

In [10]:
d1_array.dtype

dtype('int32')

In [11]:
d1_array.ndim

1

In [12]:
d2_array.ndim

2

In [13]:
d1_array.size

3

In [14]:
d2_array.size

9

In [15]:
d1_array.shape

(3,)

In [16]:
d2_array.shape

(3, 3)

In [20]:
one=np.ones((3,3),dtype=int)
print(one)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
one=np.zeros((3,3),dtype=int)
print(one)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
d2_array.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
arr_reshape = np.reshape(d2_array, (3,2))
print(arr_reshape)

[[1 2]
 [3 4]
 [5 6]]
